version: '3'

services:

  dynamodb:
    image: lambda-chatgpt-api/dynamodb
    container_name: lambda-chatgpt-api-dynamodb
    build:
      context: ./dynamodb
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - lambda-chatgpt-api-dynamodb-store:/home/dynamodblocal/data
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    networks:
      - lambda-local

  dynamodb-admin:
    container_name: lambda-chatgpt-api-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
    networks:
      - lambda-local

  console:
    image: lambda-chatgpt-api/console
    container_name: lambda-chatgpt-api-console
    build:
      context: ./console
      dockerfile: Dockerfile
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    volumes:
      - ../:/app
    networks:
      - lambda-local

  app:
    image: lambda-chatgpt-api/console
    container_name: lambda-chatgpt-api-app
    build:
      context: ./console
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ../app/:/app
    ports:
      - 3000:3000
    networks: 
      - lambda-local
    command: /bin/bash -c "npm run dev"

  # s3:
  #   image: minio/minio:RELEASE.2021-10-10T16-53-30Z
  #   container_name: lambda-chatgpt-api-s3
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ACCESS_KEY: "access_key"
  #     MINIO_SECRET_KEY: "secret_key"
  #   command: [ "--compat", "server", "/data", "--console-address", ":9001" ]
  #   volumes:
  #     - ./s3/data:/data
  #   networks: 
  #     - lambda-local

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   container_name: lambda-chatgpt-api-mailhog
  #   ports:
  #     - 8025:8025
  #     - 25:1025
  #   networks:
  #     - lambda-local

volumes:
  lambda-chatgpt-api-dynamodb-store:

networks:
  lambda-local:
    external: true